// Étape · service worker único: guia + navegador + mapa + fontes, cache-first. Versão 396fcc4e
const C = 'etape-app-396fcc4e';
const A = ["./", "./fonts/Archivo-400-normal-latin-ext.woff2", "./fonts/Archivo-400-normal-latin.woff2", "./fonts/Archivo-600-normal-latin-ext.woff2", "./fonts/Archivo-600-normal-latin.woff2", "./fonts/Archivo-700-normal-latin-ext.woff2", "./fonts/Archivo-700-normal-latin.woff2", "./fonts/ArchivoNarrow-400-italic-latin-ext.woff2", "./fonts/ArchivoNarrow-400-italic-latin.woff2", "./fonts/ArchivoNarrow-400-normal-latin-ext.woff2", "./fonts/ArchivoNarrow-400-normal-latin.woff2", "./fonts/ArchivoNarrow-600-normal-latin-ext.woff2", "./fonts/ArchivoNarrow-600-normal-latin.woff2", "./fonts/BigShouldersDisplay-700-normal-latin-ext.woff2", "./fonts/BigShouldersDisplay-700-normal-latin.woff2", "./fonts/BigShouldersDisplay-800-normal-latin-ext.woff2", "./fonts/BigShouldersDisplay-800-normal-latin.woff2", "./fonts/BigShouldersDisplay-900-normal-latin-ext.woff2", "./fonts/BigShouldersDisplay-900-normal-latin.woff2", "./fonts/fonts.css", "./icon.svg", "./index.html", "./manifest.webmanifest", "./nav/app.js", "./nav/bike3d.svg", "./nav/data-mod.js", "./nav/data.js", "./nav/fonts/Archivo-400-normal-latin-ext.woff2", "./nav/fonts/Archivo-400-normal-latin.woff2", "./nav/fonts/Archivo-600-normal-latin-ext.woff2", "./nav/fonts/Archivo-600-normal-latin.woff2", "./nav/fonts/Archivo-700-normal-latin-ext.woff2", "./nav/fonts/Archivo-700-normal-latin.woff2", "./nav/fonts/ArchivoNarrow-400-italic-latin-ext.woff2", "./nav/fonts/ArchivoNarrow-400-italic-latin.woff2", "./nav/fonts/ArchivoNarrow-400-normal-latin-ext.woff2", "./nav/fonts/ArchivoNarrow-400-normal-latin.woff2", "./nav/fonts/ArchivoNarrow-600-normal-latin-ext.woff2", "./nav/fonts/ArchivoNarrow-600-normal-latin.woff2", "./nav/fonts/BigShouldersDisplay-700-normal-latin-ext.woff2", "./nav/fonts/BigShouldersDisplay-700-normal-latin.woff2", "./nav/fonts/BigShouldersDisplay-800-normal-latin-ext.woff2", "./nav/fonts/BigShouldersDisplay-800-normal-latin.woff2", "./nav/fonts/BigShouldersDisplay-900-normal-latin-ext.woff2", "./nav/fonts/BigShouldersDisplay-900-normal-latin.woff2", "./nav/fonts/fonts.css", "./nav/fuel.js", "./nav/geo.js", "./nav/gps.js", "./nav/guide.js", "./nav/icon.svg", "./nav/icons.js", "./nav/index.html", "./nav/manifest.webmanifest", "./nav/render.js", "./nav/report.js", "./nav/sensors.js", "./nav/session.js", "./nav/store.js", "./nav/styles.css", "./nav/telemetry.js", "./nav/track.js", "./nav/ui.js", "./nav/voice.js", "./nav/weather.js"];
self.addEventListener('install', e => { e.waitUntil(caches.open(C).then(c => c.addAll(A)).then(() => self.skipWaiting())); });
self.addEventListener('activate', e => { e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k !== C).map(k => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then(r => r || fetch(e.request).then(x => {
    if (x.ok && e.request.url.startsWith(self.location.origin)) { const cl = x.clone(); caches.open(C).then(c => c.put(e.request, cl)); }
    return x;
  }).catch(() => caches.match('./index.html'))));
});
